### ISSUE TITLE
Installation process does not work

### ISSUE THREAD

**Issue by laceja** [qcubed/qcubed#1131]
I've tried both the composer installation and just downloading the qcubed and running the included installation procedure and neither one of the works at all.  I give up!

**Comment by vaibhav-kaushal** [comment]
It has been fixed. Can you try again?

**Comment by laceja** [comment]
So far, the only problem I have is, after installation, I must change all permissions so the configuration checker can access files, like configuration.inc.php.  Other than that it appears to be working.

Thanks for fixing it!

**Comment by laceja** [comment]
Okay, here are the problem I now experience with the install:

1.  Installation only works with composer.  If you want to download the zip file and install it, all the scripts are setup for composer so, they don't work.

2.  The installation process (composer) does not set the DB_CONNECTION_1 in the configuration.inc.php file.

3.  If you want to later change DB_CONNECTION_1 and/or add a DB_CONNECTION_2, you must manually modify the codgen_settings.xml file.  It doesn't get recreated based on the configuration.inc.php.

4.  Can't find instructions on how to install plugins.

**Comment by matthiaz** [comment]
I decided to start a new qcubed project to document what the installer does and figure out why multiple people are having problems. This might be a bit verbose, but I'm hoping this has enough information to get this fixed.

PHP version I tested on:
```
[matthias@matthiast60 NetBeansProjects]$ php -v
PHP 5.6.29 (cli) (built: Dec  8 2016 09:37:24) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

Running the standard command mentioned in the documentation
```
[matthias@matthiast60 NetBeansProjects]$ composer create-project qcubed/app-starter nonpaint
Installing qcubed/app-starter (1.0.5)
  - Installing qcubed/app-starter (1.0.5)
    Downloading: 100%         

Created project in nonpaint
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing qcubed/composer (dev-master 06ceb3b)
    Cloning 06ceb3bd4136ac61da5e0a9560bc21cc51ca7dc1 from cache

  - Installing qcubed/qcubed (dev-master 81da734)
    Cloning 81da73411cc39f4a4bc99cf20921f20c73cdf3c9 from cache

qcubed/qcubed suggests installing ezyang/htmlpurifier (dev-master)
qcubed/qcubed suggests installing fortawesome/font-awesome (^4.6)
Writing lock file
Generating autoload files
[matthias@matthiast60 NetBeansProjects]$ 
```
So that looks ok, next step: navigate to http://localhost/nonpaint on firefox:
```
( ! ) Warning: require_once(project/includes/configuration/prepend.inc.php): failed to open stream: No such file or directory in /home/matthias/NetBeansProjects/nonpaint/qcubed.inc.php on line 9

Call Stack
#	Time	Memory	Function	Location
1	0.0010	246056	{main}( )	.../index.php:0
2	0.0010	247512	require_once( '/home/matthias/NetBeansProjects/nonpaint/vendor/qcubed/qcubed/assets/php/qcubed.inc.php' )	.../index.php:6
3	0.0043	249000	require( '/home/matthias/NetBeansProjects/nonpaint/vendor/qcubed/qcubed/assets/qcubed.inc.php' )	.../qcubed.inc.php:3
4	0.0044	251104	require( '/home/matthias/NetBeansProjects/nonpaint/vendor/qcubed/qcubed/qcubed.inc.php' )	.../qcubed.inc.php:2
5	0.0048	253728	include( '/home/matthias/NetBeansProjects/nonpaint/qcubed.inc.php' )	.../qcubed.inc.php:7
```
Mmm, so the install didn't work as expected, lets start digging: 

http://localhost/nonpaint/index.php redirects to header('Location: vendor/qcubed/qcubed/assets/php/_devtools/installer/index.php'); , why would it try to include qcubed.inc.php?

Lets check out the file:
line 6 mentions: require_once('../../qcubed.inc.php');
So we're going up 2 directories. 
so we're actually doing: require_once('vendor/qcubed/qcubed/assets/php/qcubed.inc.php');

That file contains:
// Include prepend.inc to load QCubed
require(dirname(__FILE__).'/../qcubed.inc.php');

So we're actually doing: require('vendor/qcubed/qcubed/assets/qcubed.inc.php');

Then...
```
<?php
require(dirname(__FILE__).'/../qcubed.inc.php');
```
So we're actually doing: require('vendor/qcubed/qcubed/qcubed.inc.php');


Then that file contains:
```
$configPath = "includes/configuration";

if (!defined ('__PREPEND_INCLUDED__')) {	// not already included some other way (like with .htaccess file)
	// expect this file to be in the vendor/qcubed/qcubed directory
	include(dirname(__FILE__).'/../../../qcubed.inc.php');
}
```

Since __PREPEND_INCLUDED__ is not defined, we're doing: 
include('qcubed.inc.php');
So that's how we end up at that root qcubed.inc.php file.
(notice the mixing of include, require and require_once, is there a reason for this?)


But Ok, no problem there, the qcubed requires make sense. But then the question becomes: why doesn't project/includes/configuration/prepend.inc.php exist?
According to https://github.com/qcubed/app-starter the project folder should be automatically be copied from qcubed/qcubed/install/project but that doesn't happen. 

I believe the problem lies with the renaming of qcubed/framework to qcubed/qcubed (see: https://github.com/qcubed/qcubed/commit/8e7225475f7c8eb6545503ed2314cc4b96b40ea8), but my knowledge of composer isn't sufficient to be 100% sure. Several other people have encountered the same problem, and while I can fix this manually but copying the project folder, I don't think it's a good idea to have a broken installer. New users will instantly go looking for another framework when that happens. 

Could someone with more knowledge of the app-starter or composer give me a hand? 

Thanks
Matthias

**Comment by kukrik** [comment]
I do not know if I understand exactly. But it seems to me that I had a similar problem in the past.
I see that you use the command `composer create-project qcubed/app-starter nonpaint`.

Please try `composer create-project --stability=dev qcubed/app-starter nonpaint`. I believe that the problem is resolved.

Let us know!

**Comment by matthiaz** [comment]
Hi Tiit Papp,

I didn't mention it in my first post. But I did try stability=dev as well,
same problem.

Matthias

2017-01-16 10:55 GMT+01:00 Tiit Papp <notifications@github.com>:

**Comment by kukrik** [comment]
Ok. I had previously avoided this problem and used a second command. Because it's a problem for me, was previously known, it must eventually make the issue times.

**Comment by vaibhav-kaushal** [comment]
@matthiaz I had talked about the same problem in some other issue. Renaming from **framework** to **qcubed** had caused problems. Some of which I had solved and the installer had worked for me at that time. So what is the sureshot solution? 

## The solution
There are two parts.
## Part 1
The problem here (by @matthiaz, at least) seems to be all those includes and requires, `dirname(__FILE__)` and those `../`s in the codebase. Now, they are there to make sure that the autoloader of QCubed is getting instantiated properly because without the code we write wont be working. 

Hence, it is important that we get the autoloading right. Since we already have composer installed (and we install QCubed using composer), we can use the autoloader in Composer.

For that to work well, we will have to do the namespacing and tell Composer that QCubed uses PSR-4 (or PSR-0, but PSR-4 is better). That way, we can get rid of all the requires and the first part of problem will be taken care of. 

### Part 2 

I think something in composer might have changed which fails the current setup and project folder is not created. This one needs investigation. Again, the rename from 'framework' to 'qcubed' might have caused issues here too.

**Comment by olegabr** [comment]
@vaibhav-kaushal, there are no urgent need in PSR-0 or PSR-4. A `classmap` feature can be used for now: https://getcomposer.org/doc/04-schema.md#classmap

**Comment by vaibhav-kaushal** [comment]
@olegabr Yes, for now! For the bugfix, we can use this.

However, we had the goal of namespacing in version 3.1 anyways. Why not do it?

**Comment by spekary** [comment]
Because namespacing is a lot of work, and has ramifications for the organization of the entire project. Its a 4.0 goal right now. Namespacing will break current projects. We should try not to break code within a major version number.

**Comment by vaibhav-kaushal** [comment]
@spekary Can we decide on the folder structure though?

**Comment by spekary** [comment]
See #1063

**Comment by spekary** [comment]
The installer is working again. The problem was that the list of package types being allowed (qcubed-qcubed) was not matching the package type for the framework. They are now both qcubed-framework. Let's leave this alone. There is no reason to change it.
