### ISSUE TITLE
codegen templates

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1141]
Are there any possibility for codegen to generate responsive forms templates  like bootstrap ?

**Comment by matthiaz** [comment]
Checkout the bootstrap plugin https://github.com/qcubed/plugin_bootstrap



2016-11-23 16:00 GMT+01:00 Vladimir Makreski <notifications@github.com>:

**Comment by kukrik** [comment]
@vmakre probably thought it that generated forms of Bootstrap to Draft.

It is possible, but it is a very big job. @vaibhav-kaushal had earlier suggested the idea of a single, can not remember where, apparently template theme...

**Comment by spekary** [comment]
I do it often. See the bootstrap plugin. The process is a combination of using bootstrap style templating (you can see examples in the plugin examples), and also changing the actual type of the control. You can change the control type by right clicking on a control and using the model controller designer, and then codegenning again.

**Comment by vmakre** [comment]
I really hate "right click" on codegen controls , as i never understand all this mechanism of changing something and after this i need to generate again!!!.  I think codegen should be reworked from scratch and this process to be divided in prats like db orm model, panels , forms and finally templating . We can make one file with all templating snippets for all form objects  , and this can be very easy to change and to make modifications and make many custom templating files. Also when we render views  $this->object->Render() we can render object from template snippet (good for uniformity).   We can create one template class (object) with properties for all possible form objects(controls) but only template logic without codegen code, and also we can use this for rendering form objects . Second thing is process of codegen to be divided by what i need to regenerate instead of all process from scratch , what if i need to change only one table and i need to regenerate this one table forms. If we use codegen a lot , this means on every regenerate we can break modifications we made before. Or maybe you have some better practice?

**Comment by spekary** [comment]
Development in general is moving towards a process where you try to do as much as you can using a declarative process vs. imperative. Meaning, how much can you accomplish by just describing what you want using config files and things like that, vs. having to write code?

The codegen process fits this movement very well. The database itself becomes declarative, creating an entire application to start with. 

The right click process is simply a way to further this by editing a config file that can describe more about the ui objects being created by the database. Instead of being limited to having a VARCHAR generate a QTextBox, you can now customize each field to create any kind of QControl that is compatible with a VARCHAR field. I originally went down the path of putting these config options in the comments in the database, but it turns out there is a pretty low limit on the amount of text you can store in the Comments, so it all had to go in a separate config file. Its not meant to be a UI designer, and perhaps that is what you are expecting? That you could make changes and see them instantly appear? That would be great, but quite a difficult app to create, and maintain the flexibility that QCubed currently has. Feel free to work on that though.

Codegenerated code is nice in that it can be parsed and optimized by the PHP7 and HHVM engines, and both of those are moving down paths of doing code analysis and compilation to improve performance.

There are other approaches. There are ORMs that expect you to describe your database structure on your own, and unpack your data on your own, but they are reaching the limits of their usefulness because of how slow they are. You can have the application look up in real time what control to attach to each field vs. having that baked in to the generated code. I find generated code better because I don't have to try to debug or rely on a complex system to draw the UI. The code is all there, making the debug process and the process of overriding easier.

I don't find doing a lot of codegenerating that big of a problem. Even if I have to make a single small change, it only takes about 5 seconds to regenerate the code (~50 tables at this point). 

All that said, we are already planning on doing some of what you are asking. The ORM will be broken out so it can be used separately from QCubed, and that will mean the codegen process will need to be more modular and be broken out separately as well.

However, in terms of flexibility, the current codgen process is quite flexible. You can override any template file to make your own templates. You can make multiple template groups, and each one override the previous group installed. 

Regarding "making one file that has all templating snippets for all form objects", you might want to elaborate. That is how the templates were in 2.0, and it was very inflexible. The new system allows any plugin UI object to define how to create its own code, making it possible for the plugins to work with the templates. The only way to do that is to have a separate file for each object.
