### ISSUE TITLE
Database profiler doesn't work when utf8 is set in config 'encoding' => 'utf8'

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1142]
When i n config.inc.php mysql encoding param is set with  'encoding' => 'utf8'
then dbprofiler shows error.
Error is 
MySqli Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB (Mysql) server version for the right syntax to use near 'SET NAMES utf8' at line 1

in QMySqliDatabase.class.php in line  87
	// Set NAMES (if applicable)
	if (array_key_exists('encoding', $this->objConfigArray))
		$this->NonQuery('SET NAMES ' . $this->objConfigArray['encoding'] . ';');
   
This is only in db profiler but not in normal querries

**Comment by kukrik** [comment]
@vmakre, this is a known problem. I could not detect the error: https://github.com/qcubed/qcubed/issues/1101.
Although, this idea that I suggested the encoding, this is because the saved umlauts database correctly: https://github.com/qcubed/qcubed/issues/936.

But here's the interesting thing. Not the problem on production server. Only the development server perhaps a computer that has the problem still.

Please see: http://qcu.be/examples/index.php.
