### ISSUE TITLE
LoadAll in ORM should be generator based

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/qcubed#1145]
We are currently loading everything from the database into an array. This is a problem when there is not enough memory to hold all the objects. As such, it is very easy that some day when the database is big, the developer is going to hit the limit and the program will crash. 

We should implement the `LoadAll` method in our generated ORM using PHP generators so that the user does not accidentally run into memory leaks. The logic that I have thought of till now is: 

1. The `LoadAll` method always gets **1000** items. The number **1000** is a **safe bet** for most cases. This can be customizable. 
2. It **yields** one element from the 1000 which it had queried and updates the internal counter of how many items were returned.
3. If it has finished yielding all 1000 objects, it can query the database again to get another set (1001-2000) and start returning them. 
4. If database returns 0 results, the function will **return** and finish its run. 

Thoughts? 

PS: I realize that Generators are available in PHP 5.5 and above. Hence, we will have to make PHP version 5.5 is a minimum for version 3.1

**Comment by spekary** [comment]
LoadAll should Load All. Your idea for using generators is a good one though, but give it another name (LoadCached?). However, how different is this from QueryCursor? Maybe it should use the Cursor approach to get each time? Probably should be tested to see which is more efficient.

**Comment by vaibhav-kaushal** [comment]
I have found the solution to the problem with this method (I am generating these for my ORM classes):

```php
public static function LoadAllViaGenerator($intObjectCountPerChunk = 1000) {
            $intOffset = 0;
		    $intTotalCount = RandomData::CountAll();
		    while ($intOffset <= ($intTotalCount-1)) {
                $objRandomDataArray = RandomData::QueryArray(
                    QQ::All(),
                    QQ::Clause(
                        QQ::OrderBy(QQN::RandomData()->Id),
                        QQ::LimitInfo($intObjectCountPerChunk, $intOffset)
                    )
                );
                foreach ($objRandomDataArray as $objToYield) {
                    yield $objToYield;
                    $intOffset++;
                }
		    }
			// All objects returned.
			return null;
		}
```

**Comment by spekary** [comment]
That looks reasonable. The only thing I am wondering is if there are better answers to the problem. Why do you need to read 100K objects? Are you doing some kind of calculation on them, or are you dumping them to a file or something? Also, again I have to wonder if using a cursor to walk through the result set wouldn't be more efficient, because you are basically letting the database engine manage the process of reading the data in chunks, which should be more efficient than doing it in PHP.

But, that said, I don't see a problem with generating this code. Its just that its kind of specialized and most people won't need it. It seems like something that should be put in a local template, and you could maybe share it as a gist or something like that so the community knows about it.

A bigger issue here is that that the model generation is going to start to grow significantly. As we move towards a more full featured CRUD implementation in the ORM, it could generate a lot of code. I don't think that is a big problem, but some developers don't like having a lot of unused code hanging around, so we might want some way of turning on and off parts of the ORM generator. Then ideas like this one could be included, and defaulted to "off", and a developer could use an option to turn it on. Just a thought. Might be tough to maintain.

**Comment by spekary** [comment]
Oh, there is one problem with this code though. You aren't allowing clauses to be sent in to the query from the outside. However, clauses would pose a problem. There is a kind of bug in the code when using a limit clause combined with an array expansion clause. They don't play nice together, because the limit happens before the array expansion, and so the expanded array might not have all its data.

So, if you allow clauses, you need to check the clauses to make sure there are no array expansions. I believe the cursor code in the ORM also does this check currently.

**Comment by vaibhav-kaushal** [comment]
This was a solution for my own case and I did not want to pass in any clause for my usecase so I did not consider that anyway.
