### ISSUE TITLE
Undefined GET property or variable in 'PanelName' class: ClassName

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1155]
I have codegen form and i want to manipulate panel objects from Form class.
I can't get property or variable from pnlPanelName object??. I can see in debugger all child objecta are initialized and all properties are here. Are panel objects protected from outside manipulation ? and how i can access them? . I found a way though metacontrol(modelcontrol) like $this->pnlPanelName->mctPanelName->OBJControl-> ...   , is this only way to modify panel objects?

**Comment by spekary** [comment]
Firstly, are you talking about v2 or v3 codegen? Also, I assume you are talking about the edit panel?

The latest code creates one panel object in the form. The reason is that panel can be reused. It can be in a top level form, or a dialog, or sub panel.

That panel object creates a number of other objects inside of it. For code encapsulation, if you want to do something with those objects, you either need to create a function to do what you want and put it in the override class, or expose them through getters or by making those objects public. They are not public by default. 

However, it also might be a case of needing to rethink your application logic. The panel encapsulates all the edit objects related to a table. The table might change, and the idea is if the table changes, the panel grows. The panel object is not supposed to solve all problems though. Its just a start of a CRUD type application. Perhaps what your trying to do needs something more customized?

What are you trying to do from outside the panel?

**Comment by vmakre** [comment]
I can't get property value even if I change it to public  , maybe  with some public function or getters will solve this. But for now i can access it via methods of metacontrol . 
I have timer counting and changing value of txtObject in panel . All javascript interactions (alerts , timers) must stay in end Form not in panel code as I know.
