### ISSUE TITLE
How to check that the necessary plug-ins are available?

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#1183]
@spekary, please share suggestions, how to control that whether plugins Bootstrap and QBootstrap  are installed before.

I would like to make a plug-in, please see my question: https://github.com/qcubed/qcubed/issues/1151.

I think something similar solution. But this may not be the best solution.

I suggest that probably could be checked, for example, `/vendor/composer/installed.json`.

There's scan required plugins: `"name": "twbs/bootstrap"` and `"name": "qcubed/plugin_bootstrap"`.

If there are none, then throw an error message, "Please before installing  Bootstrap and QBootstrap".

What do you think about this and how to solve correctly?

**Comment by spekary** [comment]
The standard way to handle this is just to put your requirements in the require section of your composer.json file. Composer will handle downloading the dependencies. 

If you really want to test, just test to see if the class exists.
```
$blnQbootstrapInstalled = class_exists('\QCubed\Plugin\Bootstrap\Bootstrap');
```

For twitter bootstrap, which is css and javascript only, you will need to check for the existance of that directory in the vendor directory.

**Comment by kukrik** [comment]
Thanks! I will let you know later, that's how I can make the plugin...

If I have any questions, I ask for advice again.

**Comment by vaibhav-kaushal** [comment]
@spekary, @olegabr  and @kukrik I think we should build our plugins as just stand-alone repositories and not as composer plugins. It would take effort but standardizing it would make it easier for everyone to build new ones. We could also start placing hooks inside our workflow so that triggers could be set in Plugins.

**Comment by kpirbhai** [comment]
Just my 2 cents....I think the ease of including plugins via composer has improved things so much. If someone is able to build a plugin, then they are likely able to figure out how to make the composer file for it. We could write a tutorial on how to create a plugin that is installable via composer.

**Comment by spekary** [comment]
Maybe you can describe more of what you mean by triggers? But building plugins now is much easier than building them before, and much easier to maintain. Perhaps the hardest part is registering them with Packagist, but that is not too difficult.

Our custom composer installer does an extra step currently of moving the contents of the "install" directory it finds in a plugin into the project folder so that the user can have a place to override the default plugin behavior. From a composer perspective, that is the only difference between a qcubed plugin and a regular repository. If you don't include an install directory, there is no difference.

What specifically did you have in mind?

**Comment by spekary** [comment]
I want to add an additional comment regarding plugins. A QCubed plugin is for a contribution that someone wants to make available to the community, and supported by the community. Now that we have composer, there really is no reason why someone can't just make their own feature, put it in their own repository, add it to Packagist on their own, and then tell the community about it. If they want to maintain control of the feature, but still take pull requests, this is a great way to handle the situation.

Perhaps the one other thing that could be added is a way to tell qcubed about the plugin so that the plugin's examples would show up under the plugin manager. 

I think the easiest way to do this would be to modify the plugin manager (which really now is just a plugin lister), to look in the vendor/composer/installed.json file and look at everything that has type qcubed-plugin, and not just the files in the vendor/qcubed directory. I will close this and add that as a feature request.
