### ISSUE TITLE
another blank page when moved to production

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1211]
I think problem is with php version.
Error is:
> Parse error: syntax error, unexpected '[', expecting ')' in /home/public_html/qcubed/qcubed/includes/base_controls/_utilities.inc.php on line 158

php is 5.3.29 , i have other qcubed projects in this host but this is newest qcubed.
I'm caught in a trap?.
command is: ` return call_user_func_array([$obj, $strRenderFunc], $aParams);`

**Comment by matthiaz** [comment]
http://php.net/manual/en/language.types.array.php

*As of PHP 5.4 you can also use the short array syntax, which replaces array() with [].*

PHP 5.3.29 does not support this new array syntax. Do you have a way to update to a newer PHP version?

**Comment by spekary** [comment]
QCubed v3 requires php 5.4 or above. There were a number of reasons to do that, but I can't remember all of them. Least wise, 5.4 is not even supported any more. We will probably keep at 5.4 for a while, at least until Google App Engine decides to support something greater than 5.5.

**Comment by vaibhav-kaushal** [comment]
Yes, you need PHP 5.4 for installing QCubed 3.x. @spekary Traits were introduced in 5.4 We use QModelTrait which increases efficiency and improves management of the code to some extent.

**Comment by spekary** [comment]
Wow, you have a great memory. That seems like so long ago, so much code....

**Comment by spekary** [comment]
We should put a check somewhere so people don't go down the rabbit hole. I am surprised that Composer didn't check or warn or something.

**Comment by spekary** [comment]
Oh, I see why. He installed with composer, but then copied it to a production server that was a lower version. Probably a common issue. We should issue a warning and check for the minimum version, probably in prepend.inc.php file.

**Comment by vmakre** [comment]
Yes my local development is php7 with composer (no problem installing packages). But i will solve my problem with hosting provider allowing me to change php version with htaccess file. I hope i will do it , because php5.3 is very old platform but we always tend to work with newest technology :)

**Comment by vaibhav-kaushal** [comment]
@vmakre I have faced a similar situation.

**Comment by vmakre** [comment]
Yes close it ,  minimum requirement for framework was not met :)

**Comment by matthiaz** [comment]
@spekary  "We should issue a warning and check for the minimum version, probably in prepend.inc.php file."

I don't think we should. The way you work with composer is that you run 
`composer update `
on your development environment, and test if everything works. 

Then you upload your composer.lock file to production (or commit to version control) and run 
`composer install` 
This will install the exact same version you tested because it will use the lock file. 

See: https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control

Copying the vendor folder is in my opinion a bad way of deploying. 

So yeah... I vote to close this issue. (vmakre seems to agree ;-) )
