### ISSUE TITLE
memory footprint and performance

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1243]
I am getting around 3.5 MB of memory_get_usage  for simple web page .
When i open Form with around 55 object controls inside (most checkboxes and inputboxes) i got 7 MB .
This sounds good for me that qcubed don't eat a lot of memory like other frameworks , we must expect 3-3.5MB for "hello world" page , but  performance 
isn't brilliant.  I  don't understand all Form::Run mechanism and all that 
 javascript dynamic pieces of code which renders inside body. So is there a place for performance optimizations in the future  , or this depends on framework logic . What you think about performance measurement and how to find and point code bottleneck ?.

**Comment by spekary** [comment]
You have to profile both in PHP and in javascript to figure this out. I have worked a lot to reduce the amount of traffic between the browser and the server. We can still improve that by implementing changes in controls through javascript calls rather than re-rendering the whole control, but its tricky. 

I have also spent a lot of time optimizing the move from a query into the model objects. Not sure there is much more to do there. My tests show that its pretty fast now, faster than even trying to cache the objects.

If browser refresh is a problem, we could try to be a backend to React, which uses shadow-dom to improve the drawing speed.

Using Redis as the formstate and session state handler will improve things. See @vaibhav-kaushal 's recent contribution there. Have you tried the current 3.1 branch?

But PHP is a bit of a pig. If you really are looking for sub 50ms responses, PHP is not going to do it I think. That is why I have been dabbling in GoLang. I think there is potential to port much of QCubed there, and do it more modularly. Some of the pieces have already been done by others.

Running HHVM might improve things a bit, since it precompiles the code, and then caches the most recent pages. It would be interesting to do a comparison between PHP7 and HHVM on our framework.

Another thing that slows down web pages is the many javascript and css files that get loaded. I spent a little time trying to at least get those loading in parallel. Be sure you are using RenderScripts in your <head> tag so that the css scripts will get loaded by the browser in parallel. Perhaps you could work on the deployment scripts that we have been talking about, and include a javascript and css compiler and combiner to help optimize performance on deployment?

Lots of things to try here.

**Comment by matthiaz** [comment]
Not worth the work on 3.1. Probably better to do this once q4 is back on track
