### ISSUE TITLE
QDataGrid row click event problem

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1254]
QDataGrid row click event overwrite filter (order) click bug.
Table header needs to be disabled from click row event.
From this example just click table header.
http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/datagrid/rowactions.php.
Click events works in this way:
1. First click is table header order click , databind occures.
2. Second click is table row click event . 
So this is not a bug if table header is treated as a row. Maybe this can be solved with handling these two events in php row click function. But how to find if table header is clicked?

**Comment by vmakre** [comment]
This is first row click hack:
`if ($strParameter=="") return ;`

So  this is example  row click function
```
public function dtgPersonsRow_Click($strFormId, $strControlId, $strParameter) {
        // table header row is treated as normal row so we will omit row click event
        if ($strParameter=="") return ;
        
       $intPersonId = intval($strParameter);

        $objPerson = Person::Load($intPersonId);

        QApplication::DisplayAlert("You clicked on a person with ID #" . $intPersonId .
                ": " . $objPerson->FirstName . " " . $objPerson->LastName);
    }
```
Can someone submit this ?

**Comment by matthiaz** [comment]
That feels a bit... wrong, no? The ajax request will be triggered, and then ignored by the server. Wouldn't it be better to not trigger the header row click at all?

**Comment by matthiaz** [comment]
I've checked the actual event that gets attached

QCellClickEvent line 418 of _events.inc.php
```
		public function __construct($intDelay = 0, $strCondition = null, $mixReturnParams = null) {
			parent::__construct($intDelay, $strCondition, 'th,td');
```

The third parameter of parent::__construct is the $strSelector of QEvent. So QCellClickEvent actually includes the TH. I don't think it should, and if it should we might be better off splitting this off in a seperate event, or adding a parameter for it. I'm adding a PR to remove this.

**Comment by spekary** [comment]
See #1258. 

QCellClick is very general purpose. There are reasons that we want to detect clicks on the header rows. We can't predict what a developer would want that for.

A header cell is still a cell in the table. QCellClick should respond whenever a cell in the table is clicked, whatever its tag is. QCellClick is flexible enough so that you can control what kinds of information it sends back to the action, so that you know what got clicked on.

There were two problems with the exampele:
1. The action was not detecting that we clicked on a header cell. This is simply checking if the rowId is blank.
2. The data binder was not asking for an OrderBy clause, and so the sorting was not working.

**Comment by spekary** [comment]
Oh, and thank you again for looking into this, its very valuable to have the examples checked.
