### ISSUE TITLE
Flash messages between page redirects

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1294]
I want to implement this idea into qcubed
[codeigniter-like-flashdata-in-core-php](https://stackoverflow.com/questions/12153140/codeigniter-like-flashdata-in-core-php)
It is good for showing messages when we do `QApplication::Redirect('/')  `
for example after submitting data into database and if success we want page redirect but  no 
way to show message. Or when we create new user and after submit , redirect to user_list page , we need information for new data inserted.

**Comment by spekary** [comment]
Looks like a reasonable idea. Best to do it with a plugin control, maybe a subclass of a QPanel. Our philosophy moving forward will be to use plugins for things like this so that the core is just supporting html. 

The receiving page would just need to render your control to get the message. Use javascript to hide it, or a JsTimer.

**Comment by vmakre** [comment]
As is in example 
`FlashMessage::add(' message ');`
and on every new form call
`FlashMessage::render();  or  echo FlashMessage::render();`
very simple to use , same as qcubed database profiler works.

**Comment by spekary** [comment]
That is fine, but its not core. As I said, a plugin control could work, or just giving directions on putting that in the QForm object the user controls works. (This is similar to the direction in the Bootstrap plugin of editing the QControl class to point to the Bootstrap contol class so it is injected into the project.)

But putting it in the core means everyone has that code, and it must be maintained. A plugin control would give you personal control of its maintenance. 

You don't want this on every form call, like in FormRun, because that always fires on Ajax calls too. Just tell people to call your code from FormCreate, and it should work fine.

**Comment by vmakre** [comment]
Does that means plugin can be called with namespaces without require function?

**Comment by spekary** [comment]
In v4, yes. Follow the example of the other plugins to make it Composer installable. It will auto load just by calling the namespace.

Shannon

> On Dec 15, 2017, at 1:33 PM, Vladimir Makreski <notifications@github.com> wrote:
> 
> Does that means plugin can be called with namespaces without require function?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Shannon Pekary
spekary@gmail.com

**Comment by spekary** [comment]
In v3, it will also autoload for namespaced plugins.

**Comment by kukrik** [comment]
@vmakre, maybe my first plugin gives you a hint: https://github.com/kukrik/counterup2?

**Comment by vmakre** [comment]
@kukrik  thanks , but I don't have  v4  installed , maybe will try it in next days.
I am happy with v3 , i am doing a lot of things with it , not perfect at all , but it satisfied my goals. 
I will share my experience with all of you , and tell some direction points about how things can work better.

**Comment by kukrik** [comment]
It would be very nice to share experiences and support each other. When I wanted to add a plug-in and add to V3, @spekary suggested going to v4. To learn is hard for me, but we have to move on. I'm going to be a dreadful student to be with @spekary :).

Sharing experiences and advice is very important for all of us. The QCubed framework is really very good... It's a little regrettable that the community is still small.
