### ISSUE TITLE
Question Regarding QSortable

### ISSUE THREAD

**Issue by willypowwow** [qcubed/qcubed#1312]
I'm using the Qsortable control to create a sortable list of values.   Is there any way to determine the actionparameter of one of the underlying controls in the item array when that item is Clicked?

**Comment by spekary** [comment]
I would have to see some code to know what you are doing. Generally, yes. You would simply assign QClick action to the control you are talking about. The problem is that the javascript may have a hard time differentiating between clicking to drag something, and clicking to activate the click action. Since that is controlled by jQuery UI, I don't know off the top of my head whether it can do that. Its probably best to create some kind of area in each item that the user would click in order to drag, and a different area for clicking a button.

**Comment by willypowwow** [comment]
Thank you, Shannon.  Sometimes a good night's sleep is all that is needed.  Your answer reminded me that the items being sorted are QLabels, which can have their own QClick action.  Adding that event whilst populating the list has solved my problem.
