### ISSUE TITLE
Is it latest time to upgrade to qcubed.js???

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#1315]
Perhaps this question is not well worded. We know that QCubed is so good that adding and updating data on the database side is super. There are no problems with this.

I think QCubed's biggest weakness is the **one-way** data flow to the database only. Here we need to do **two-way** data like Ajax, one simple example (different modifications may be, the idea remains the same):

```js
$(document).ready(function(){
       $('#save').click(function(){
          var id  = $('#Id').val(); 
          var firstName =  $('#firstName').val();
          var lastName =  $('#lastName').val();
          $.ajax({
              url      : url,
              method   : 'POST', 
              data     : {firstName : firstName , lastName: lastName , id: id},
              success  : function(response){
                            ('#panel).html(response)
                         }
       });
  });
```
I have long been researching qcubed.js, but I find it difficult to understand. How to make another solution?

I often use the Developer Tools Network to track data flow. I see that 'firstname' and 'lastname' data are sent to the database. This is good!

<img width="1274" alt="Screenshot 2019-04-25 at 12 56 57" src="https://user-images.githubusercontent.com/2853034/56734708-45ff5100-676c-11e9-88ef-f884b40a50c9.png">

Let's look at the response, but nothing. This is the place we need to think about and, if necessary, supplement. Apparently qcubed.js need to upgrade?

<img width="1278" alt="Screenshot 2019-04-25 at 12 57 52" src="https://user-images.githubusercontent.com/2853034/56735219-91fec580-676d-11e9-8c42-0ecb6057d8f5.png">

In many applications, this Ajax feature has already been widely implemented. We feel a great shortage of this opportunity. Also, the QCubed framework is also not poor, it is also very capable in many features. We also need to make it better.

Or have such opportunities already been made or other good practices that don't use qcubed.js or whatever...

Please actively share thoughts or good practices!

**Comment by matthiaz** [comment]
I'm unsure what you are asking.
You mention that the response has "nothing". But it clearly has a response. 

QCubed sends back which controls need to be changed. qcubed.js reads that response, and modifies the DOM to reflect the new formstate.

If you are asking to have a debug log, you can already do this.
Something like : QApplication::ExecuteJavascript("console.log('firstname = x')");

You could even make a function in the QApplication, to be able to do
QApplication::Log("lastname = y");

I remember there being a QFirebug plugin in qcubed 2, but since both qcubed 2 and firebug are deprecated, that's probably not very usefull anymore.

Also: If you want more information on what the database is doing, use database profiling.

**Comment by kukrik** [comment]
I even know that my question was not well worded. I know this QFirebug plugin, but I don't need it. This Developer Tools is for monitoring and get info, etc...

My title is now totally inappropriate, qcubed.js is well thought out. I found a decent solution by putting the necessary function in the right place:

```php
public function refresh()
    {
        parent::refresh();
        ControlBase::refresh();
    }
```
It did what is needed and is the expected result.

I am sorry to have put the wrong question. 

PS. @matthiaz, you're an active here. I have a few questions to which I hope your help and advice :)! Thanks for your quick response! 

I'm closing this topic and open new topics if needed.
