### ISSUE TITLE
btnDelete and btnCancel problem

### ISSUE THREAD

**Issue by vallter2** [qcubed/qcubed#1317]
Hi,

on QCubed v4 I have problem with btnDelete and btnCancel.

# 1
If edit panel (any panel) clear/new and click on btnCancel, its look like form is submitted but with wrong validations on fields.

# 2 
If on edit panel click on Delete button and in confirmation dialog click on Cancel, item are deleted and redirected on List panel.

**Comment by kukrik** [comment]
Hi @vallter2, you are probably new here, if so, welcome! The information you provide is not enough to understand what the real problem is. Maybe I'm smarter to ask before I am to understand...

1) The first quick question - how do the forms in Draft work?
2) If these forms work, your custom solutions may not work very well. Then you have to redesign your solution. There is not enough information here.
3) If it doesn't work for you like the ones in Draft, for example, it might be misconfigured or whatever... Have you received any error messages?

Please share more info!

**Comment by vallter2** [comment]
Hi @kukrik ,
forms is default/generated without any change, I try with fresh QCubed installation, but problem is same. 

(On image you can see what happens when click on Cancel)
![test1](https://user-images.githubusercontent.com/28445312/61171775-88227c80-a57c-11e9-9aa8-c42c3d1179a5.jpg)

**Comment by vallter2** [comment]
I fix Cancel problem with this:
$this->btnCancel->CausesValidation = false;

Problem with Delete is still active :)

**Comment by matthiaz** [comment]
old question, probably no longer important.
