### ISSUE TITLE
simple routing engine

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#612]
I am willing to implement simple routing engine in qcubed project not in core like one index,php file and roter code as plugin . I am thinking of better route/filter protection of get and post parameters and defining custom routes and class dispatcher . My question is is there any code in core doing this and is this needed for better security or not?. Also will be better for mod rewrite to work of just remove only index.php and easy rewrite customization in router with array defined as only allowed url's.  I found some good library with callable class call_user_func_array with parameters (parameters will be filtered with good regex functions) , so what are you thinking about this?

**Comment by spekary** [comment]
That is fine. A couple of thoughts: 
1. In alpha3 I did some work so that ajax posts only post changed data, rather than the entire form. That is for speed. Please make sure that continues.
2. The web in general is taking two directions: Phone enabled sites (Bootstrap, Framework, jQuery Mobile), and application in a page, where everything is done in ajax, and no routing is needed. 
3. We are still trying to keep things as straight forward for beginners as possible. I didn't like the changes that put routing information after the page in the url. Basic url + get params has always been good enough for me, and if I need more, I put info in the session. So keep it clean.

**Comment by vaibhav-kaushal** [comment]
I am currently using (already implemented a router where I have one QForm and everything is a QPanel that goes into that Form (got that idea from @scottux). The rewrite rule is a simple one (takes the request and send it to the QForm as PATH_INFO) and so it is easy to implement. 

The way I do it is - the route creator checks the Url step by step and when it reaches the end of nested switches, then it creates an object (RouteInfo object) which contains routing info. Like, if I have a product-listing page (www.example.com/products-list <http://www.example.com/products-list>) then I will write the front-controller panel to handle that request. Anything which goes after that (e.g. www.example.com/products-list/computers/keyboards <http://www.example.com/products-list/computers/keyboards>) will be handled by the Front-Controller itself. However, I can also write separate controller for that! This leaves ample room for customisation.

The QApplication::QueryString can figure out the query string inside the front-controller or I can also figure that out in the routing logic and put into the RouteInfo object. The Front-Controller class can also be put into RouteInfo object and then you can handle the request the way you like. 

I could not come up with anything simpler.

**Comment by vmakre** [comment]
Ok @spekary  i think there is problem with ajax if parameters are sent as  query string and there we cannot change this. Also there is a problem with mapping class names and form url. I have basic class dispatcher working but it is sometime buggy and problematic and i want it to be more clear and safe . I want to allow only some classes to be accessible . @vaibhav-kaushal  i know about @scottux  idea for panels but it is a little strange for me as i learned qcubed as is with forms and every file have new form . This works like www.example.com/<class-name>  is   www.example.com/index.php/<class-name> but in dispatcher it is www.example.com/index.php/controller/filename.class.php    class-name is filename of course  but sometime i want to put more directories in controller folder and  to call classes with namespaces so there is a little work to do. My idea for routing engine i got from Laravel where classes are called with call_user_func_array but this will not work as we need class to be autoloaded first and after this to call something like  Index::Run('Index','index.tpl.php')  .Or  Class:Run method  to have one more property to accept url parameters as function arguments ? .

**Comment by vakopian** [comment]
Now that we have composer, could we perhaps use a 3rd party router? For example: https://github.com/chriso/klein.php

**Comment by spekary** [comment]
Using 3rd party code would be great. I just want to make sure this isn't going to be required by the core. We should minimize dependencies on third party code for the core. Depending on jQuery has been fine, but jQuery UI has been a little bit of a hassle to maintain their many fickle changes, and sometimes difficult to fix bugs. 

Can we make it a plugin? A plugin could always depend on other 3rd party code, like the bootstrap plugin requires bootstrap to also be installed through composer.

**Comment by vaibhav-kaushal** [comment]
I was afraid of asking this, actually, thinking everyone would start asking why I want this. But seriously, slimmer is better and jQuery UI does not serve the functions of the core. It better be like a plugin!

**Comment by spekary** [comment]
Its a good question, and there is already an issue posted on this. It will have to wait. Core uses the dialog, and the draggable, droppable and resizable from jQuery UI, and those are not easily pulled out at this point. Previous owners of QCubed felt that the jQuery UI implementations were better than the QCubed ones. I think keeping jQuery UI as part of the core, and keeping it maintained, is OK for now. jQuery UI has a really nice widget engine too, which is a big plus. On the downside, it has minor conflicts with CSS frameworks like Bootstrap, but workarounds for those are available.

**Comment by vakopian** [comment]
I don't like how the discussion about routing got switched to discussing the jquery UI controls, but since I'm one of the "previous owners" of QCubed who pushed for this solution, I feel like I should defend it a little bit. So here it goes:
* I strongly believe that a web application framework should provide a rich set of UI controls. The fact that it's hard to develop and maintain such controls is exactly the reason why the framework should provide them.
* Over-reliance on plugins is what kills frameworks. Plugins always get outdated and becomes unusable. It's very rare that a plugin is able to keep up with the development of the framework.
* The work that we did on jQuery UI controls showed how a UI control plugin can and should be done in QCubed. Before those standard plugins people did random hacks to hookup existing javascript UI controls to QCubed. We basically standardized how a front-end control should be hooked to QCubed. If you've been with QCode/QCodo long enough, you may still remember the old autocomplete plugin. All I'm gonna say is that it _kinda_ worked _sometimes_.
* Not only we now have standard/recommended way of wrapping js controls, we even have automatic generators for such wrappers. I have used these generators to create several plugins myself. In fact I only use the generator for UI control plugins because it ensures that they will work as well as the core jquery UI controls.
* The work on hooking up _all_ the jquery ui controls exposed many weaknesses in the framework and pushed us to fixing them (much of this work was done by our dauntless @spekary himself). 
* To me, having and maintaining these controls in the core is another way of "eating our own dog food" - if we think our framework is good enough to allow people developing rich web applications we should be able to handle complex javascript driven controls like the jquery UI.

Over the years many people have argued and asked to remove this or that part of QCubed from "core". I've heard some people say they only want the ORM part, I also heard other people say they don't want the ORM at all. Same way, some people only want the front-end parts (QForm/QControl) and some people don't want that at all. So the "jQuery UI controls" is another one of those, some people want them some don't care for them. But let's remember that (unlike the ORM) you don't have to use those controls. Like the other components, I think the benefits of having these controls outweigh the drawbacks. Bootstrap and foundation may be more prominent now, but jquery UI is far from dead. There are many things jquery UI provides that are still not available in these other toolkits.

If you really want/need this separation, just saying "let's make it a plugin" is not enough. You'll need to _"show the code"_ and convince people why it's better. @spekary already mentioned several difficulties, and many more will be revealed once you start the coding.

**Comment by vaibhav-kaushal** [comment]
Can i just revert my previous statement and agree with you? 😁

**Comment by vakopian** [comment]
@vaibhav-kaushal - that's almost always the right solution :smile:

**Comment by vaibhav-kaushal** [comment]
@vakopian and I thought you were a serious guy. Anyways, for now I think we can keep jQuery UI. The only problem being - the generated documentation is hard to make sense of sometimes. Other than that it does not concern me (because I mostly do not use it).
