### ISSUE TITLE
Back button in browser double POST prevention

### ISSUE THREAD

**Issue by openbrian** [qcubed/qcubed#768]
Does QCubed prevent a double POST by using some mechanism like Post/Redirect/Get?  This would be useful in search forms.

https://en.wikipedia.org/wiki/Post/Redirect/Get

**Comment by spekary** [comment]
Not really. It has a loose mechanism to prevent two people from updating the same record, but its not that great.

This is a good suggestion. However, as the article says, it only fixes the problem when doing a page refresh with resubmission. It doesn't fix the problem when the person presses twice because of server lag. This would be a great feature for someone to work on :-)

**Comment by openbrian** [comment]
For search forms which don't post data, we could parameterize method here to be GET.

https://github.com/qcubed/framework/blob/master/includes/qcubed/_core/base_controls/QFormBase.class.php#L1268

**Comment by spekary** [comment]
Please elaborate. What would this help with, and how would you do it? Not sure how to detect a "search form which doesn't post data".

**Comment by openbrian** [comment]
In our website we compose a search box filled with fields, with a data grid below it.  Search is inherently a GET, not a POST.  After getting results and clicking on a single record, when the user clicks the back button, they will be returned to search results without the browser bugging them about reposting a form.

I wold parameterize the method attribute of <form>.  Create an attribute of QFormBase called strMethod and default to POST.  Any form/page that has a search form, would set $this->Method = 'GET'.

**Comment by spekary** [comment]
You are using a QServerAction instead of a QAjaxAction?

**Comment by spekary** [comment]
I mean, in response to the search field being typed in, in order to filter the results.

**Comment by openbrian** [comment]
Yes QServerAction.

**Comment by spekary** [comment]
Changing this to a GET would possibly be difficult. It would take some testing. And there are situations where it would be impossible.

In a GET, all variables are put on the browser line. This will include all the hidden inputs that QCubed uses to keep track of state. If using the FormStateHandler, it would not be possible, since the entire form state is put in a variable, and GET variables have a size limit. 

We would have to change all the places we look for these items from looking in $_POST to $_REQUEST.

Have you tried switching to an AjaxAction? That might be an easier fix. Be sure to set SaveState on your search field (assuming you are using v3).

**Comment by spekary** [comment]
This is fixed by a new 4th parameter to an event that will cause it to wait until all events have been processed before executing. This will allow the form to change, or ajax to complete, before a 2nd click is processed. Also, you should switch to a QAjaxAction, or do just a QApplication::Redirect($url, false);
