### ISSUE TITLE
Customise the code generation process

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/qcubed#815]
This is just a proposal but I think with time we are going to need it, especially given the amount of stuff we have got here, and the new plugins we have started working on. 

Right now, we have two classes which take care of the code generation process at large. One is `QCodeGen` and the other is `QDatabaseCodeGen`. Both of these methods have got certain methods in them to extract and present data from the database which they are running upon. Right now, we cannot add any custom method that we want to. If I want to treat the SMALLINT data type in a database as something special, then I have to add that method to the core somewhere. Or if I want to work with views, then I have to add something to the core as well.

In addition, if I am using two databases, one running PostgreSQL and another MySQL, then I have to use the same templates which can be problematic because I want to treat certain data types in PostgreSQL a little differently.

We need to be able to allow the developer to change the behaviour of the codegen process with two big changes: 
1. Be able to introduce new methods in the Codegen process along with templates. 
2. Templates could be installed as plugins. (It would be awesome, if we could allow certain customizations per template; I have to look into this).
3. Each database can use a different template according to the developer's needs. 
4. File generated by the default templates could be organised into namespaces. 

This is something that could solve a lot of problems we face with maintaining the templates. We can customise the templates according to need and share them with the world too. Since they can be installed easily a plugins, it would make a lot more sense :smile: 

Again, I am thinking of this for version 3.1, so there are no hurries right now.

**Comment by spekary** [comment]
Some of this is in there already.

1. Adding new methods is simply adding to QCodeGen class, or as a plugin, do it similar to the Bootstrap plugin where you create a QMyPluginCodeGen class that extends QCodeGenBase, and then direct the developer to change QCodeGen to extend QMyPluginCodeGen.
2. This is available via the static TemplatePaths variable. Templates provide customization via file override. Which means a good template breaks its various parts out into individual files so each part can be individually overridden. I recently introduced an empty file into the model templates, just so customizations can be added to a model.
3.Seems fairly easy to add by adding an option under a database section of the codegen_settings.xml file.
4. Namespaces is definitely a 3.1 thing. We should begin a discussion on what the namespaces should be.

**Comment by vaibhav-kaushal** [comment]
Great points @spekary. I will take a good look at the Bootstrap plugin and comment on this.

**Comment by lackovic10** [comment]
guys, what do you think about the idea of having the qcubed orm generator as a standalone component, which is installable via composer and usable on it's own
symfony is doing this very successfully with their [components](https://github.com/symfony/symfony/tree/master/src/Symfony/Component)
i can't promise (not sure about the amount of work i will have in the following year), but i might be able to help with this project

**Comment by vaibhav-kaushal** [comment]
@lackovic10 That is a nice idea but the problem is - the code generated by QCubed depends on QQuery. The UI part - panels, forms etc. utilise the QForm library. So essentially everything is quite interdependent. 

If you want only the ORM, you still have to have QQuery and QForms library is the only thing which you are leaving behind.

Also, where do you want to use the resulting product (just the ORM generator)?

**Comment by lackovic10** [comment]
QQuery can be made another component. not sure why we need the forms ?
i want to use the orm for a frontend implementation.
qcodo orm + symfony http foundation component + symfony routing component + a template engine + a js framework
using qforms for the frontend has proven a bad idea, i've worked on three big projects using qcodo/qcubed

**Comment by lackovic10** [comment]
another thing that i see missing in qcubed and haven't seen it added yet is a dependency injection container or a service locator, still not quite sure between the difference of these two things
i don't know the experience of you guys, but having all the business logic in the `data_classes` has  been a big pain for maintenance, a container solves this issue easily
not to forget! i see, based by the issues list, that the 3.0 version is very close to launch
i'm sure it's been a great amount of work
hats off to @spekary and all the other guys who put in the work!

**Comment by olegabr** [comment]
@lackovic10 I'm totally agree with you to make QORM a stand-alone project. It can attract more users to it, and as a result, more bug fixes and more features.

**Comment by lackovic10** [comment]
ok, can someone tell me how could we start a standalone component inside the qcubed project ?
usually, packages have an `src/ProjectName` folder, because of autoloading
i have seen an autoloading discussion somewhere here, but have no idea at which point is it
is it possible to make a folder `src/QCubed/` folder and add a `/Component` folder in it?

**Comment by vaibhav-kaushal** [comment]
I think there are some good ideas. Especially about dependency injection! About QCubed ORM - I am open to suggestions and medthodologies at this point

Sent from a rotary phone.




On Thu, Aug 11, 2016 at 11:11 PM +0530, "Ivan Lackovic" <notifications@github.com> wrote:












ok, can someone tell me how could we start a standalone component inside the qcubed project ?

usually, packages have an src/ProjectName folder, because of autoloading

i have seen an autoloading discussion somewhere here, but have no idea at which point is it

is it possible to make a folder src/QCubed/ folder and add a /Component folder in it?

**Comment by lackovic10** [comment]
ok, i see that `QForm::Run()` is still static. I would start by adding a [ContainerInterface](https://github.com/php-fig/fig-standards/blob/master/proposed/container.md) object when calling run - by adding a parameter to the [QForm::Run()](https://github.com/qcubed/framework/blob/master/includes/qcubed/_core/base_controls/QFormBase.class.php#L305)
Also would suggest including an already existing solution of containers into qcubed
I'll see if i can find some time to make a PR with my idea

**Comment by spekary** [comment]
This really part of a bigger discussion of what 3.1, or really 4.0 should look like. Part of the problem is my own doing, in that I made some architecture changes but haven't yet really documented them. Part of the reason for that is shown by your question, in that we really don't think we are "there" yet in terms of what QCubed should look like architecturally, and so its hard to put a big doc effort in if we are going to change it again fundamentally.

You are right that business logic should not go in to the data classes. But the architecture is designed so you don't have to do that. Unfortunately, in 2.2, some html generation snuck in to the genereated data classes, and that encouraged bad programming. That has been deprecated, and so we are back on track hopefully.

I was putting most of my business logic in forms, but I too found that over time, this was a mistake. 

The current architecture is designed so that:
1. Data classes (as in the data class subclasses that live in project/model) are there to abstract the data model. For the most part, whenever you access the database, you should put the code in the data class. That means essentially you should try as much as possible to keep all QQuery references in the data class. This is not entirely possible, because sometimes you need to describe your clauses, how you want to expand the query, and limits and sorting, from the business logic. We should think about a better way to do this so that the ORM completely abstracts the data model from the SQL. That is what will make it possible to insert NoSQL databases into a project when needed.
2. Form objects for the most part should just be a shell for form level things - mostly navigation buttions.
3. Most of the business logic should now go in the main panel, and that interacts with the model connectors, both of which you can control.

I have found that architecture to be very functional going forward, and pretty flexible as the data schema evolves over time. As I use it, I am still working out the kinks, but it seems to be working. I love the idea of dependency injection. I am fuzzy on its value in an architecture that mainly uses overrides. And I hesitate to complicate the architecture further. If we can make it optional, that would be good.

Re: adding a container interface to Run, its a good idea, just remember that QCubed realies on being able to serialize the form and save and recall that serialized form every time it enters and exits on server and ajax calls. Some of the dependency injection I have seen relies on lamda functions and other structures that are not serializable. But as long as the definition of the object is available either by explicit includes, or through the autoloader, it should work.

I think we should move the discussion to seperate issues where we can further flesh out a roadmap to the next version of QCubed, and then bake it into a Wiki. I think its fantastic that people are getting a vision of what QCubed can become. But there is a lot or work ahead. PHP7, HHVM, and the PSRs are driving some of this, but also modern architecture paradigms like dependency injection, mobile first UI development, automated testing, javascript frameworks, etc. Dependency injection and an ORM rework are both good places to start. 

Re: ORM, some goals have been discussed here in other threads, I have a number of goals that I will move to a differenct discussion, and we can think about where it can live in the directory tree. It is related to what we want the directory tree to look like after we add namespaces.

**Comment by lackovic10** [comment]
i will try to push some code i feel it more useful than too much discussion, because there are lots of things to discuss, and even more to fix
i think that keeping the business logic in `QForms` and `QPanels` is not a good idea.
here is an example
```
protected function btnRegister_Click($formId, $controlId, $actionParameter)
{
    $user = new User();
    $user->setName();
    .....
    .....
    // add friends
    // other actions
    ....
}
```
the code above is NOT reusable, not testable and contains all the problems that come out of those two things
i believe the business logic needs it's own layer
what i do is the following:
```
```
protected function btnRegister_Click($formId, $controlId, $actionParameter)
{
    $this->getContainer()->get('manager.register')->register($requestParameters);
}
```
I also think the idea of having the methods which interact with the database is not a good idea
Here is my suggestion
```
class UserRepository
{
    public function find($userId)
    {
        return User::Load($userId);
    }

    public function findAllByFirstName($firstName)
    {
        $sql = 'select * from user where first_name = "' . $firstName . '"'; // needs input escaping
        
        return User::InstantiateDbRow(User::GetDatabase()->Query($sql);
    }
}
```
these are simple examples but should be enough to show the idea
it's easy to inject repository classes like this into managers, which gets rid of the static methods, which cause so much spaghetti code

**Comment by spekary** [comment]
Sometimes. That approach is great for some situations. 

I think the main point is that there needs to be an intermediary between the UI and the database. Typically this is the "C" in MVC. Currently, the connectors are designed for this, but they assume a rather strong correlation between the UI and the model, which is typical of a beginning project. Your flow is typical of a maturing project, when business logic takes over and creates a better user experience. We need a transition process between the two. It needs to be approachable by beginning users. Your right that such business logic should not live in the current structures, but in a separate part of the program. This is really dependent on the skill of the programmer.

Testability is a great point. Unit tests are OK, but can't test flow from form to form. User level testing through something like Codeception looks OK, but appears hard to configure and slow to run, and not sure it gives us the ability to examine internal state. I think we can create a testing framework inside of QCubed that can perform functional and business logic testing. Its not a replacement for the other two, but an addition, that allows tests to drive the UI using javascript and proceed from form to form, with intermediate checkpoints to test internal state.

We need a way for the UI to drive querying though. In particular, the datagrids need some knowledge of the data structure in order to filter and sort. Also, selection lists need to be populated from the database. What are your thoughts on how to do those?

**Comment by spekary** [comment]
Also, I am intrgued as to how your method could help solve the problem of needing to pass data between multiple panels and the form object.

**Comment by spekary** [comment]
Also, see #1063 and #1064 for answers to your quetion about a future ORM direction. Please add to the discussions there.

**Comment by lackovic10** [comment]
`Also, I am intrgued as to how your method could help solve the problem of needing to pass data between multiple panels and the form object.`
it's very easy, with the container.
in a QForm:
```
$this->getContainer()->get('repository.user')->find($userId);
```
in a QPanel:
```
$this->objForm->getContainer()->get('repository.user')->find($userId);
```

**Comment by spekary** [comment]
These topics are covered in other places.
