### ISSUE TITLE
Plugin structure for v3

### ISSUE THREAD

**Issue by olegabr** [qcubed/qcubed#868]
I have a general issue for plugin system in v3. It should support not only controls, but any other extensions, like:
- codegen
- database tables
- QQ
- ... any other qcubed extension or completely non-qcubed code

Additionally, the control's plugins support should include an ability to specify i18n files.

To achive that, I propose the plugin structure to be equal the whole qcubed structure. assets, includes, e.t.c. Any part can be omitted if the plugin does not needs it. Think of it as a virtual layers on top of the qcubed core.

The uniform structure has two goals:
1. the ability to use all qcubed architecture features in the plugin
2. the ability to implement simple build tools to prepare project for production: one can move all `assets` from all plugins and the qcubed itself into the one web-accessible place, and all `includes` to anothe non-web-accessible place.

Additionally, it simplifies the learning curve - no need to learn two different structures - the qcubed itself and it's plugins.

But for me the main goal is the first - the ability to use all qcubed architecture features in the plugin. I want to have plugins for the whole login infrastructure, plugin for the whole user settings infrastructure, etc. It should have an ability to inject some tables into the database and provide code to work with it on all levels. It means codegen, db and i18n support at minimum.
And I want to have a QQ plugins to support database-specific features too.

That is why plugin should have the same structure as the qcubed itself, I believe - it should have an ability to extend any qcubed aspect. Any.

**Comment by spekary** [comment]
A lofty goal. Its a little different from the current plugin goals, as the current plugins are designed to add to the capabilities of the core, rather than replace them.

Replacement is probably achievable through the autoloader. It might require namespacing qcubed to get that to work.

QCodo had a replacement style plugin architecture. It was based on patches, and I found that to be unworkable as whenever the core changed, you would have to recreate the patches.

**Comment by spekary** [comment]
Alsop, we should move this to 3.1. We are really trying to get to release. Your bug finds are helpful for that.

**Comment by olegabr** [comment]
ok for 3.1

**Comment by spekary** [comment]
Some of this is done in our custom composer installer, which allows a plugin to have an "install" directory that gets copied to the project directory. We need to add more infrastructure to allow other types of overloading, but this is a start. 

Some other things are achievable by telling the programmer to base a class off the plugin class. For example, the bootstrap plugin works well when the programmer QControl class extends the Bootstrap/Control, since that class extends QControlBase.

There is more to do here.

**Comment by spekary** [comment]
I am closing this. Composer makes it very difficult to directly edit anything in the vendor directory. However, its all classes. You can subclass anything and override anything. If there is some particular file you are having difficulty with, reopen this and post that file here. Also, v4 opens up a lot more built-in ways to override behavior. I can't think of any particular behavior that is not overridable just by subclassing a file.
