### ISSUE TITLE
Move the qcubed forum to ost.io?

### ISSUE THREAD

**Issue by olegabr** [qcubed/qcubed#95]
Can we move the qcubed forum to ost.io?

http://ost.io/qcubed/framework

**Comment by davidmclark1** [comment]
Need the Examples SQL tables files.   Trying to train a new person and we uploaded the latest version and set it up...but as far as I can see it does not have the SQL file.    Install worked but there were not tables... 
Can anybody point me to the example tables.   We dumped our long ago because qcu.be was always there...but seems to be gone now.   
Thanks 
David
dclark@bwkip.com

**Comment by spekary** [comment]
https://github.com/qcubed/framework/blob/master/assets/_core/php/examples/mysql_innodb.sql

or

https://github.com/qcubed/framework/blob/beta-3.0/assets/php/examples/mysql_innodb.sql
