### ISSUE TITLE
Determine if control value changed

### ISSUE THREAD

**Issue by kpirbhai** [qcubed/qcubed#979]
I'm wanting to add some functionality to QControl so that I can determine if the control value has actually changed by checking 'defaultValue' against 'value' using javascript.

The problem I have it that I honestly have no idea how to grab the value being returned from my JavaScript function from inside of QCubed.

My function is:

```
function ctrlValueChanged(strControlId) {
    var ctrl = document.getElementById(strControlId);
    if (ctrl.value != ctrl.defaultValue) {
        return true;
    } else {
        return false;
    }
}

```

And I'm calling it in QControl as:

```
                public function ValueHasChanged() {
                    return QApplication::ExecuteJsFunction('ctrlValueChanged', $this->ControlId);
                }
```

No value is returned. Any help would be greatly appreciated!

**Comment by spekary** [comment]
This is an old question, but I will answer and close. You need to think about when you need this information. Whatever user action is triggering the need is where you would get the informatio as a JsReturnParam on the action or event. You can then look at that param as that action parameter on your event handler.

Incidentally, the latest version of QCubed v3 may make it so that you do not need this. Values are only sent from the form when something changes now (the whole form was sent in v2), and v3.1 goes an extra step and only updates the database for db fields that have changed.
