### ISSUE TITLE
One question is how best to use the search?

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#996]
Very inconvenient to have to write your search words in uppercase. For example, if in the tables have names: John, Kendall, Wendy, and other names, then search can not find, for example, in small letters: john, kendall, wendy, etc... Then the table is empty.

I think it must be able to look for differences in case of words!

Datatables allows flexible searching, for example, the first example: http://localhost/qcubed-shannon-dev/vendor/qcubed/plugin/datatables/examples/datatables1.php

Another example of the search does not work - http://localhost/qcubed-shannon-dev/vendor/qcubed/plugin/datatables/examples/datatables2.php.

What do you think of that would be needed to improve the ability to search?

EDIT: I must explain this issue. This problem does not only apply inside datatables, but also search not capable with "Drafts Form View"...

**Comment by spekary** [comment]
This is a problem with your database I think. QCubed is just doing a LIKE search. Googling for this shows that you need to set your database up with case insensitive colation if you want case insensitive searches. 

We COULD change the templates so that they insert the LOWER function to force it to be case insensitive no matter what your database collation is. Do you think we need this?

**Comment by kukrik** [comment]
I understand your question. 

One of my client believed that this option would be more comfortable.

That he everyday should look clients database through the first big letter and then look for the small letters. For example, in database is names: John and Josiah. 

Why not look for instance of the first syllables: jo or Jo?

That's why I like datatables you first example (whether look immediately the first big letter or not): http://localhost/.../vendor/qcubed/plugin/datatables/examples/datatables1.php.

Both options should be available.

What do others think?

**Comment by spekary** [comment]
The example only works because it is not using Ajax binding and not using SQL to search for the data. The search is happening in Javascript and done by the datatables plugin. To search for a larger data set, you need to use ajax binding, which will force the search to go through SQL. At that point, it is totally up to you how you want to search, as it depends on your query. You need to override BindData and implement a query that will do case-insensitive searching, since your database is case-sensitive. There is nothing we can do in qcubed, since your the one who controls the query and the database configuration.
