### ISSUE TITLE
Some additional input parameters on creating new object

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#997]
Hi , we always want to have simplest code so when we create for example new button , we need to create new object and to change and to add new properties. What if we make some simplification of process instead of "create object" , "add text property" , "add click event"  to be 
in one process when creating new object 
$newbutton = new QButton($parent, $text, $click_event )
at first for most used properties text and click for example to be second or third parameter.
Or some array style for example 
$newbutton = new QButton($parent, array( "text" => "some text" , "click" => "some click event" ))
I think this will be compatible with old code .

**Comment by matthiaz** [comment]
@vmakre 
I would prefer using an array because the property list will quickly get too big to handle. 
I'll that in our my own projects, I add static creators for things I often need.

Example:
`$button = QButton::Create($parent, array("Text"=>"some text", "OnClick"=>...))`

This doesn't impact the way people use new QButton. 

Second thing I'd like to add. I also use these static functions for ListBoxes. Usually when I need a list of a certain object I create a GetListBox function that creates a listbox, adds items,... 
Example:
`$listbox = Person::GetListBox($parent)`

**Comment by spekary** [comment]
@matthiaz, we are trying to move away from the data objects creating html code. The right place for something like that would be the PersonConnector object.

@vakre, the advantage to how we do it now is that editors can read the comments and help you fill in as you type. It is also usable by the ModelConnectorEditor. Long parameter lists or arrays are opaque to an editor, so you have to remember what the names of the parameters are, the editor can't help you.

Although, I like the idea of an OnClick action, and some other common event handlers as a shortcut.
